package org.mycore.pi.exceptions;

public class MCRDatacenterAuthenticationException extends MCRDatacenterException {

    public MCRDatacenterAuthenticationException() {
        super("Error with authentication!");
    }

}
